# Generated by Django 4.2.9 on 2024-01-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='car',
        ),
    ]
