# Generated by Django 4.2.9 on 2024-02-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_carbuyer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carbuyer',
        ),
    ]
